### ISSUE TITLE
Missing verification variant in PageProperty enum

### ISSUE THREAD

**Issue by ThomasLesmann** [46ki75/notionrs#109]
Toying around, I happened upon `Error: deserialization error: unknown variant 'verification', expected one of 'button', [...]` when creating a page as a child to a wiki page: `notion.create_page().page_id("<page in a wiki>").send().await?` The page gets created, but the response can't get parsed.

A variant for the verification property is missing in PageProperty. Curiously there is an extra PageProperty::Button variant which doesn't appear in the api, unless the api documentation is just being weird?

The verification property type is documented here: https://developers.notion.com/reference/page-property-values#verification

Not yet familiar with PRs, could help out though.

**Comment by 46ki75** [comment]
Thank you for reporting this issue!

The problem arises because the `Verification` page property is not yet implemented, and this is not due to a discrepancy in the Notion API documentation.

To provide more details: when you use `create_page`, the page is successfully created, and the API call itself works fine. However, the issue occurs during the deserialization of the API response. Since the `Verification` variant is not implemented in the current library, deserialization fails, which results in an error even though the page is created successfully.

We will implement support for the `Verification` property in the next alpha release. Please wait a little longer, and thank you for your patience!

**Comment by 46ki75** [comment]
The bug has been fixed in the latest release, `v1.0.0-alpha.21`. Unit tests and integration tests passed without any issues (the `verification` property only appears in wiki pages, and this test case was missed). Please verify if it works correctly with the latest version.

**Comment by ThomasLesmann** [comment]
Yes, it works as expected now with the new release. Thank you kindly.
