### ISSUE TITLE
Remove `new()` Method in Favor of `Default` and `From`

### ISSUE THREAD

**Issue by 46ki75** [46ki75/notionrs#88]
## Motivation

The `new()` method, while common in OOP for user-friendly initialization, is redundant in this context. Most use cases are covered by the `Default` trait, and more complex scenarios are handled via `From`. Removing `new()` simplifies the codebase and avoids duplication.

## Tasks  

- [ ] Remove all `new()` method implementations.  
- [ ] Replace usages with `Default::default()` or `From` where applicable.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Removed the `new()` method from the `Client` struct implementation and replaced its usage with `Default::default()`. Updated the `secret()` method to take `&mut self` instead of `self` to allow method chaining after default initialization.

You can review changes in this commit: https://github.com/mnmnk43434/46ki75-notionrs-88/commit/7086b46693c0cb6056368e058e1edf4fa6488a12.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
